server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb+srv://campushareAdmin:campusharePassword@clustercampushare.qhbomhf.mongodb.net/?retryWrites=true&w=majority
      database: User
    